kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# 컨트롤 플레인
- role: control-plane
  extraPortMappings:
  # DevSecOps 웹 서비스 포트
  # - 외부에서 웹 애플리케이션 접근용
  # - 호스트 접근: http://localhost:30080
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Kibana 서비스 포트 (내부 통신용)
  # - Elasticsearch 데이터 시각화 도구
  # - 내부 서비스 통신용
  - containerPort: 30601
    hostPort: 5601
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Elasticsearch HTTP API 포트
  # - 로그 및 데이터 저장소
  # - REST API 엔드포인트
  # - 호스트 접근: http://localhost:9200
  - containerPort: 30920
    hostPort: 9200
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Logstash Beats 입력 포트
  # - 로그 수집기
  # - Filebeat 등의 데이터 수집기와 통신
  # - 호스트 접근: localhost:5044
  - containerPort: 5044
    hostPort: 5044
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Kibana 웹 인터페이스 포트
  # - Elasticsearch 데이터 시각화 웹 UI
  # - 호스트 접근: http://localhost:30601
  - containerPort: 5601
    hostPort: 30601
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Jenkins 웹 인터페이스 포트
  # - CI/CD 파이프라인 관리 웹 UI
  # - 빌드 및 배포 모니터링
  # - 호스트 접근: http://localhost:8080
  - containerPort: 30800
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Jenkins JNLP 에이전트 포트
  # - Jenkins 워커 노드 연결
  # - 분산 빌드 에이전트 통신
  # - 호스트 접근: localhost:50000
  - containerPort: 30850
    hostPort: 50000
    listenAddress: "0.0.0.0"
    protocol: TCP

# 워커 노드 1: 웹서버
- role: worker
  labels:
    node-type: webserver
    purpose: apache-php

# 워커 노드 2: Jenkins
- role: worker
  labels:
    node-type: auto
    purpose: jenkins

# 워커 노드 3: 백업 DB
- role: worker
  labels:
    node-type: backup-db
    purpose: backup-storage

# 워커 노드 4: ELK
- role: worker
  labels:
    node-type: elk
    purpose: elk-stack

# 워커 노드 5: 로그 DB
- role: worker
  labels:
    node-type: log-db
    purpose: log-storage

# 워커 노드 6: 모니터링
- role: worker
  labels:
    node-type: monitoring
    purpose: monitoring